version: '3'
services:
  biliup:
    image: ghcr.io/biliup/caution:latest
    container_name: biliup
    restart: unless-stopped
    ports:
      - "<HOST_ADDRESS>:<HOST_PORT>:19159"
    volumes:
      - /path/to/save_folder:/app
    environment:
      # - PUID=0 # Uncomment if you want to change the default user 
      # - PGID=0 # Uncomment if you want to change the default group